# template configuration

build_dir:               build
run_dir:                 run
# run_dir:               /storage/carmelo/lense_thirring/bh3/run
h5filepath:              "{sequence_index:04d}/bh_{run_number:04d}.h5"

dt:                      1e-5
sampling_dt:             0.125

groundstate:
    output_filename:     groundstate.h5
    runtime:             15


excite:
    init_filename:       groundstate.h5
    breakpoint_filename: excite_br.h5
    output_filename:     excite.h5
    runtime:             0.2
    globals:
        # excite
        Ue:              0.75
        cx:              15
        cy:              0
        sx:              5
        sy:              1

imprint_pair:
    init_filename:       groundstate.h5
    breakpoint_filename: imprint_pair_br.h5
    output_filename:     imprint_pair.h5
    runtime:             3
    fixed_x_index:       43
    fixed_y_index:       128
    globals:
        # vortex pair
        xv:              30
        dv:              2
        v1:              -1
        v2:              1

realtime:
    init_filename:       imprint_pair_br.h5
    output_filename:     realtime.h5
    runtime:             100
    fixed_x_index:       43
    fixed_y_index:       128


continue:
    init_filename:       init_continue.h5
    output_filename:     continue.h5
    runtime:             50


globals:
    alpha:               0.0065

    # confining potential
    radius:              50
    U0:                  10000

    # sink potential
    Gamma:               500
    sigma:               3

    # vorticity
    nu:                  10

    # damping (groundstate & imprint_pair)
    Lambda:              1
